// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Apartament.Data;

#nullable disable

namespace Proiect_Apartament.Migrations
{
    [DbContext(typeof(Proiect_ApartamentContext))]
    partial class Proiect_ApartamentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proiect_Apartament.Models.Apartament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("ProprietarID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProprietarID");

                    b.ToTable("Apartament");
                });

            modelBuilder.Entity("Proiect_Apartament.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Proiect_Apartament.Models.CategorieApartament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ApartamentID")
                        .HasColumnType("int");

                    b.Property<int>("CategorieID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ApartamentID");

                    b.HasIndex("CategorieID");

                    b.ToTable("CategorieApartament");
                });

            modelBuilder.Entity("Proiect_Apartament.Models.Proprietar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeProprietar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Proprietar");
                });

            modelBuilder.Entity("Proiect_Apartament.Models.Apartament", b =>
                {
                    b.HasOne("Proiect_Apartament.Models.Proprietar", "Proprietar")
                        .WithMany("Apartamente")
                        .HasForeignKey("ProprietarID");

                    b.Navigation("Proprietar");
                });

            modelBuilder.Entity("Proiect_Apartament.Models.CategorieApartament", b =>
                {
                    b.HasOne("Proiect_Apartament.Models.Apartament", "Apartament")
                        .WithMany("CategorieApartament")
                        .HasForeignKey("ApartamentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Apartament.Models.Categorie", "Categorie")
                        .WithMany("CategorieApartament")
                        .HasForeignKey("CategorieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartament");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Proiect_Apartament.Models.Apartament", b =>
                {
                    b.Navigation("CategorieApartament");
                });

            modelBuilder.Entity("Proiect_Apartament.Models.Categorie", b =>
                {
                    b.Navigation("CategorieApartament");
                });

            modelBuilder.Entity("Proiect_Apartament.Models.Proprietar", b =>
                {
                    b.Navigation("Apartamente");
                });
#pragma warning restore 612, 618
        }
    }
}
